#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";

# Start commands for application
require Mojolicious::Commands;
require Velicio;
my $commands = Mojolicious::Commands->new(app => Velicio->new);
push @{$commands->namespaces}, 'Velicio::Command';
$commands->run(@ARGV);
